"""accounts: User and RoleBinding -- identity and per-event authority.

FEAT-02, initial schema. Serves D-01 and D-03: our authorization lives in
RoleBinding, NOT in Django's global permission framework, because a global
framework cannot express "the same person judges trk_03 and trk_07 with
different authority" (bible/05 §3). User therefore has no PermissionsMixin,
and User.has_perm returns False -- see reviewer/accounts/models.py.

`visitor` is deliberately absent as a stored role value: a visitor is the
absence of a binding, and storing it would mean every anonymous request
creates a row.

`source_key` on both tables is D-11: the round-trip property is byte-identical
INCLUDING natural keys, and "modulo generated IDs" would let a dropped column
pass.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
import reviewer.accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Django admin gate only. Product authority is a RoleBinding.",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
                "ordering": ["email"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("email", ""), _negated=True),
                        name="accounts_user_email_not_empty",
                        violation_error_message="An empty email is not an identity.",
                    )
                ],
            },
            managers=[
                ("objects", reviewer.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RoleBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("participant", "Participant"),
                            ("judge", "Judge"),
                            ("organizer", "Organizer"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_bindings",
                        to="events.event",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_bindings",
                        to="events.track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_role_binding",
                "ordering": ["event", "role", "track_id", "user_id"],
                "indexes": [
                    models.Index(
                        fields=["event", "user"], name="accounts_rb_event_user_idx"
                    ),
                    models.Index(
                        fields=["event", "role", "track_id"],
                        name="accounts_rb_event_role_trk_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role", "judge"), ("track__isnull", True), _connector="OR"
                        ),
                        name="accounts_rolebinding_track_only_on_judge",
                        violation_error_message="Only a judge binding may be track-scoped.",
                    )
                ],
            },
        ),
    ]
