"""reviews: Assignment, Review, Score -- and the one correct redundancy in the schema.

FEAT-02, initial schema. Serves D-01 (isolation in the data-access layer) and
bible/05 §5, §6, §10.

Review.judge and Review.project are DENORMALISED from Assignment on purpose.
The isolation query is "every review by judge J" and "every review on a project
in track T"; both are single-table filtered reads, and with the composite
index (event, judge, status) they are index scans. Without the columns every
isolation check is a join, and the filter that must never be forgotten lives
one hop further from the row it constrains. The cost is two sources of truth,
held by unique(judge, project) here and by one writing function in code.

Score.weight_applied is SNAPSHOTTED at submission time. If an organizer edits
weights mid-judging, existing reviews must not silently change meaning;
Event.rubric_weights_locked_at prevents that on the normal path and the
snapshot makes it impossible on the abnormal one.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        ("projects", "0001_initial_schema"),
        ("rubrics", "0001_initial_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch", models.CharField(blank=True, max_length=64)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("batch", "Batch"),
                            ("algorithmic", "Algorithmic"),
                        ],
                        default="batch",
                        max_length=12,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("declined", "Declined"),
                        ],
                        default="assigned",
                        max_length=12,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="events.event",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_assignment",
                "ordering": ["event_id", "project_id", "judge_id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("declined", "Declined"),
                        ],
                        default="assigned",
                        max_length=12,
                    ),
                ),
                ("overall_comment", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_conflicted", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.assignment",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="events.event",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.project",
                    ),
                ),
                (
                    "rubric_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review",
                "ordering": ["project_id", "judge_id"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.SmallIntegerField(blank=True, null=True)),
                (
                    "weight_applied",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=6
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="rubrics.criterion",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_score",
                "ordering": ["review_id", "criterion_id"],
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["event", "judge", "status"], name="reviews_asg_event_judge_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["event", "project"], name="reviews_asg_event_proj_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("judge", "project"), name="reviews_assignment_uniq_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["assigned", "in_progress", "submitted", "declined"])
                ),
                name="reviews_assignment_status_known",
                violation_error_message="Unknown assignment status.",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["event", "judge", "status"], name="reviews_rev_event_judge_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["project", "status"], name="reviews_rev_project_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["event", "submitted_at"], name="reviews_rev_event_sub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("judge", "project"), name="reviews_review_uniq_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["assigned", "in_progress", "submitted", "declined"])
                ),
                name="reviews_review_status_known",
                violation_error_message="Unknown review status.",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "submitted"), ("submitted_at__isnull", False)),
                    ("status__in", ["assigned", "in_progress", "declined"]),
                    _connector="OR",
                ),
                name="reviews_review_submitted_has_timestamp",
                violation_error_message="A submitted review must carry its submission timestamp.",
            ),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["criterion_id", "value"], name="reviews_score_crit_value_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("review", "criterion"), name="reviews_score_review_crit_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("value__isnull", True),
                    models.Q(("value__gte", 1), ("value__lte", 10)),
                    _connector="OR",
                ),
                name="reviews_score_value_in_range",
                violation_error_message="A score outside 1..10 cannot be interpreted on any rubric.",
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_applied__gt", 0)),
                name="reviews_score_weight_positive",
                violation_error_message="A snapshotted weight must be greater than zero.",
            ),
        ),
    ]
