"""io: RunSnapshot -- the manifest for a bulk export or import.

FEAT-02, initial schema. Serves D-11 and bible/05 §8, §8a, §8c.

The round-trip property is "export -> import -> export is byte-identical
INCLUDING every source_key". That is a deliberate correction: the earlier
phrasing "byte-identical modulo generated IDs" quietly removes the property,
because a dropped column just makes the second export shorter and nothing
asserts the length.

`schema_version` plus `compatible_with` exist so an unknown version is REFUSED
rather than guessed -- a wrong guess silently drops data, and a refusal costs
an afternoon. The manifest is a contract, so it is in the schema before the
exporter that has to honour it (FEAT-07).

`dry_run` is a column and not only a flag because the feature an organizer
actually wants is a dry run that reports WITHOUT WRITING, and the report has to
survive as a row: counts in, counts out, orphan references, duplicates
detected, near-duplicate submissions flagged.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("export", "Export"), ("import", "Import")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="planned",
                        max_length=12,
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("compatible_with", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField()),
                ("manifest", models.JSONField(default=dict)),
                (
                    "archive_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("report", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_snapshots",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "io_runsnapshot",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "kind", "-generated_at"],
                        name="io_snapshot_idx",
                    )
                ],
            },
        ),
    ]
