# Generated by Django 5.2.17 on 2026-09-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io", "0001_initial_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassthroughColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("table", models.CharField(max_length=64)),
                ("column", models.CharField(max_length=128)),
                ("value_type", models.CharField(default="unknown", max_length=16)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passthrough_columns",
                        to="io.runsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "io_passthroughcolumn",
                "ordering": ["table", "column"],
                "unique_together": {("run", "table", "column")},
            },
        ),
        migrations.CreateModel(
            name="PassthroughRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_key", models.CharField(max_length=255)),
                ("value", models.JSONField()),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="io.passthroughcolumn",
                    ),
                ),
            ],
            options={
                "db_table": "io_passthroughrow",
                "ordering": ["column_id", "row_key"],
                "unique_together": {("column", "row_key")},
            },
        ),
    ]
