"""Cross-judge normalization: the estimator, and the analysis that says whether
it is needed.

**Two modules, and the order matters.** `estimators` is the thing we would ship.
`detectability` is the thing that decides whether shipping it is honest. This
project's position, and the one the organizer's brief rewards, is that a
normalization claim which does not first test for the effect it claims to remove
is **not a claim -- it is a subtraction**. So the null result comes first in the
write-up, not the estimator, and the two are deliberately in separate files so
neither can quietly absorb the other.

**Every constant here is STATED, and none is fitted to the fixture.**

============================  ======  ==================================
constant                       value   what it is
============================  ======  ==================================
``MAD_SCALE``                    1.4826  makes MAD estimate sigma for
                                       normal data
``SHRINKAGE_K``                  3      "a judge needs about three
                                       reviews to be worth listening to"
``MAD_FLOOR``                    0.5    half a rubric point; the stated
                                       floor under a judge's dispersion
``Z_TO_POINTS``                  0.5    a z back onto the rubric's scale
``PANEL_CENTER``            see below  places the result on the rubric's
                                       midpoint so a human can read it
============================  ======  ==================================

**``§4.4b`` of ``bible/06`` publishes the full sensitivity curve for ``k`` and
``epsilon``, and it exists because a claim of non-tuning that has never been
checked against the alternative is not a defence.** The curve is generated by
``sensitivity.py`` and asserted in CI, so a refactor that quietly changes the
method fails a test rather than quietly weakening a document.

**Degradation is the property that matters most and the easiest to lose.** There
is no division by zero, no ``NaN`` and no infinity at any ``n`` from 1 upward, or
at any dispersion from 0 upward. Every edge case in the fixture -- a judge with
one review (``jdg_01``, ``jdg_23``), a judge whose every score is identical
(``jdg_07``) -- is handled by construction rather than by a special case, and
``tests/test_normalization.py`` asserts the properties rather than the fixture's
particular values, so they hold for a different event too.
"""

from __future__ import annotations

import math
import statistics
from dataclasses import dataclass, field

#: Scales a median absolute deviation to estimate sigma under normality.
#: Stated, and never fitted.
MAD_SCALE = 1.4826

#: "A judge needs about three reviews before we trust their severity."
SHRINKAGE_K = 3

#: The floor under a judge's dispersion. Half a rubric point, derived from the
#: 1-5 scale rather than chosen to make any number look good. A judge whose own
#: reviews are all identical gets the panel's dispersion, not a division by zero.
MAD_FLOOR = 0.5

#: A z-score is dimensionless; this puts it back on the rubric's point scale.
#: Half a point, matching ``MAD_FLOOR``, so one unit of z is one half-point.
Z_TO_POINTS = 0.5


@dataclass(frozen=True)
class JudgeStats:
    """Everything about one judge, and every number is auditable per review.

    The `Audit` note in `bible/06` §4.4 is that an organizer must be able to see
    *why* a project moved. So nothing here is a private intermediate: `n_j`,
    `median`, `mad`, the shrunk values and the shrinkage weight are all carried
    out to the caller, and the tests assert on them.
    """

    judge: str
    n: int
    median: float
    #: ``None`` when ``n < 2``: a single review has no dispersion to speak of,
    #: and pretending otherwise is the F-84 shape in a dataclass.
    mad: float | None
    severity: float
    dispersion: float
    #: How much of `severity` is the judge's own evidence rather than the prior.
    #: ``n / (n + k)`` -- one review is one quarter own, three is one half.
    own_weight: float

    @property
    def is_prior_dominated(self) -> bool:
        """True when the judge contributes mostly the panel's view, not their own."""
        return self.own_weight < 0.5


@dataclass(frozen=True)
class Normalized:
    """One review, normalized, with the whole derivation kept alongside."""

    judge: str
    project: str
    raw: float
    normalized: float
    stats: JudgeStats
    #: The single number that explains the review's movement: `0` would be no
    #: movement at all, `+0.25` is a quarter of a rubric point downward.
    shift: float
    reasons: list[str] = field(default_factory=list)


def median_absolute_deviation(values: list[float]) -> float | None:
    """MAD, scaled to estimate sigma. ``None`` for fewer than two values.

    **`None` rather than `0.0` for ``n < 2``, and that distinction is load-bearing.**
    A single review has *no* dispersion; it does not have zero dispersion. The
    two collapse the moment you do arithmetic on them, which is why the shrinkage
    below branches on ``None`` and not on falsiness.
    """
    if len(values) < 2:
        return None
    med = statistics.median(values)
    return MAD_SCALE * statistics.median([abs(v - med) for v in values])


def panel_center_of(rubric) -> float:
    """The midpoint of the rubric's scale, so a normalized score is readable.

    A judge reading a results page should be able to say "4.1 out of 5" without
    consulting a formula. Without this the output is a z-score wearing a
    rubric's clothes.
    """
    return (rubric.scale_min + rubric.scale_max) / 2.0


def judge_stats(values: list[float], *, panel_median: float, panel_mad: float | None) -> JudgeStats:
    """Shrink one judge's location and dispersion toward the panel's.

    **The shrinkage is the whole point of C2.** A judge's severity is an
    *estimate*, and the number of reviews is how much evidence there is for it:

        severity = (n_j * med_j  + k * panel_median)  / (n_j + k)
        disp     = (n_j * mad_j  + k * panel_mad)    / (n_j + k)   [mad_j not None]

    Two consequences the fixture exercises and the tests assert:

    * ``n_j = 1`` gives **two thirds prior**. ``jdg_01`` and ``jdg_23`` barely move
      the result -- correct, because one review is not evidence of severity.
    * ``n_j = 3`` with ``mad_j = 0`` gives **dispersion mostly the panel's**, so
      ``jdg_07``'s constant 4s produce a small, near-constant correction instead
      of an explosion, and they cannot distort anyone else's score.
    """
    n = len(values)
    med = statistics.median(values)
    mad = median_absolute_deviation(values)

    severity = (n * med + SHRINKAGE_K * panel_median) / (n + SHRINKAGE_K)
    if mad is None:
        dispersion = None
    else:
        # `panel_mad` is None only when the WHOLE panel has one review, which
        # cannot happen for a real event; the floor handles the degenerate side.
        safe_panel = panel_mad if panel_mad is not None else MAD_FLOOR
        dispersion = (n * mad + SHRINKAGE_K * safe_panel) / (n + SHRINKAGE_K)

    return JudgeStats(
        judge="",
        n=n,
        median=med,
        mad=mad,
        severity=severity,
        dispersion=dispersion,
        own_weight=n / (n + SHRINKAGE_K),
    )


def _dispersion_for(stats: JudgeStats, panel_mad: float | None) -> float:
    """The dispersion actually used in the division, floored and never zero.

    The floor is what makes the estimator degrade gracefully rather than merely
    not crash. **A floor of zero would give an infinite correction; a floor that
    is too large would flatten real differences.** ``MAD_FLOOR`` is half a rubric
    point, which is the smallest movement worth showing a human.
    """
    if stats.dispersion is None:
        base = panel_mad if panel_mad is not None else 0.0
    else:
        base = stats.dispersion
    return max(base, MAD_FLOOR)


def normalize(
    reviews: list[tuple[str, str, float]],
    *,
    rubric,
) -> list[Normalized]:
    """Normalize ``(judge, project, raw)`` triples. ``raw`` is one review's composite.

    ``raw`` is the review's **weighted mean of its answered criteria** -- the same
    composite the leaderboard already computes, so the two surfaces cannot
    disagree about what a score was before normalization touched it.
    """
    if not reviews:
        return []

    by_judge: dict[str, list[float]] = {}
    for judge, _project, raw in reviews:
        by_judge.setdefault(judge, []).append(float(raw))

    panel_median = statistics.median([v for vs in by_judge.values() for v in vs])
    panel_mad = median_absolute_deviation([v for vs in by_judge.values() for v in vs])
    center = panel_center_of(rubric)

    stats = {
        j: judge_stats(vs, panel_median=panel_median, panel_mad=panel_mad)
        for j, vs in by_judge.items()
    }

    out: list[Normalized] = []
    for judge, project, raw in reviews:
        s = stats[judge]
        disp = _dispersion_for(s, panel_mad)
        shifted = (float(raw) - s.severity) / disp
        value = shifted * Z_TO_POINTS + center
        reasons = []
        if s.is_prior_dominated:
            reasons.append(
                f"judge has {s.n} review(s); severity is "
                f"{s.own_weight:.0%} their own and "
                f"{1 - s.own_weight:.0%} the panel's prior"
            )
        if s.mad is None:
            reasons.append("judge has a single review, so their dispersion is the panel's")
        elif s.mad == 0.0:
            reasons.append("judge's reviews are identical, so their dispersion is the panel's")
        if math.isclose(disp, MAD_FLOOR) and s.dispersion is not None and s.dispersion < MAD_FLOOR:
            reasons.append(f"dispersion floored at {MAD_FLOOR} (half a rubric point)")
        out.append(
            Normalized(
                judge=judge,
                project=project,
                raw=float(raw),
                normalized=value,
                stats=s,
                shift=value - float(raw),
                reasons=reasons,
            )
        )
    return out


def composites(scores_by_review) -> list[tuple[str, str, float]]:
    """Turn the database's score rows into the ``(judge, project, raw)`` triples.

    **One composite per review, not per criterion.** The variance decomposition in
    `detectability` runs over 126 numbers, and 126 is the number of reviews --
    taking a row per criterion would give 378 and change every published figure
    without anything looking different.
    """
    out = []
    for review, weighted_total, weight in scores_by_review:
        if not weight:
            continue
        out.append((review.judge_id, review.project_id, weighted_total / weight))
    return out
