"""Publication: the results hash, and the claim that a stranger can recompute it.

``bible/05`` §9b, and the property is not "we computed a hash". It is **"anyone
holding the export can recompute it"** -- which is what turns the threat model's
J-10 from *detected* into *detectable by a third party*, and the difference
between a claim and a control.

Every test here is arranged so it can fail. The centrepiece exports the database,
wipes it, imports it, and recomputes the digest from the restored rows: **the
escape hatch and the publication claim are the same property viewed from two
sides.**
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from reviewer.audit import publication

pytestmark = pytest.mark.django_db

BOOKKEEPING = ("io.runsnapshot", "io.passthroughcolumn", "io.passthroughrow")


@pytest.fixture
def raw_fixture():
    root = Path(__file__).resolve().parents[1]
    return json.loads((root / "fixtures.json").read_text(encoding="utf-8"))


@pytest.fixture
def loaded(raw_fixture):
    from reviewer.events.models import Event
    from reviewer.importer import loader as loader_module

    loader_module.load(raw_fixture)
    return Event.objects.get(pk="evt_01")


@pytest.fixture
def organizer(loaded):
    from reviewer.accounts.models import RoleBinding
    from reviewer.isolation import Actor

    binding = (
        RoleBinding.objects.filter(event=loaded, role="organizer").select_related("user").first()
    )
    assert binding is not None, "the fixture ships an organizer"
    return Actor.for_user(loaded, binding.user)


@pytest.fixture
def audit_trail(loaded):
    """Real audit entries, appended through the real writer.

    **A fresh test database has an empty audit chain**, so ``chain_head`` correctly
    returns ``""`` and a publication written from it would replicate nothing --
    which is the ``blank=True`` default doing its job. Asserting against an empty
    chain would have made D-09 look like it worked when it had not run at all.

    So the trail is generated by ``audit.chain.append``, the same function
    ``just check`` exercises, rather than by inserting rows directly. **A test
    that hand-builds the thing it is testing is testing its own fixture.**
    """
    from reviewer.accounts.models import RoleBinding
    from reviewer.audit.chain import append

    judge = RoleBinding.objects.filter(event=loaded, role="judge").select_related("user").first()
    for index in range(3):
        append(
            loaded,
            "review.submitted",
            actor=judge.user,
            object_type="review",
            object_id=f"rev_{index}",
        )
    return loaded


@pytest.fixture
def judge_credential(loaded):
    """A ``JudgeCredential``, built here because **nothing else builds one.**

    F-97: the loaded fixture contains **zero** ``JudgeCredential`` rows and **zero**
    ``SignedRecord`` rows, and grepping ``src/`` for ``JudgeCredential.objects``
    returns only the model definition. Both tables ship with complete schemas --
    ``JudgeCredential`` even has the key-volume fields -- and no writer, which is
    exactly the defect F-71 found for ``AuditEntry`` at FEAT-06: a contract
    invented at the same moment as the schema it describes.

    **So this fixture is not a convenience, it is the evidence.** It builds the row
    by hand precisely because the product does not, and every test using it tests
    replication logic rather than a data path that exists. The signing increment is
    what closes the gap, and until it does, "D-09 is implemented" means "the
    replication is implemented and there is not yet anything to replicate to" --
    which is the sentence a reader is owed.
    """
    from reviewer.accounts.models import RoleBinding
    from reviewer.credentials.models import JudgeCredential

    judge = RoleBinding.objects.filter(event=loaded, role="judge").select_related("user").first()
    assert judge is not None, "the fixture ships judge bindings"
    return JudgeCredential.objects.create(
        event=loaded,
        judge=judge.user,
        public_key="ed25519:" + "a" * 64,
        signature="",
        record_hash="c" * 64,
    )


@pytest.fixture
def signed_record(loaded, audit_trail, judge_credential):
    """One ``SignedRecord``, built directly -- see ``judge_credential`` for why.

    **Which is the honest order:** the publication claim is worth having before
    the signature exists, because D-09's replication target is the *statement*, and
    the statement is a JSON document rather than a cryptographic construct. So the
    replication can be built and tested now, and the signing fills in later
    without changing what replication means.
    """
    from reviewer.credentials.models import SignedRecord

    return SignedRecord.objects.create(
        event=loaded,
        judge=judge_credential.judge,
        credential=judge_credential,
        statement={"predicateType": "https://slsa.dev/provenance/v1"},
        envelope={"payloadType": "application/vnd.in-toto+json"},
        record_hash="f" * 64,
    )


class TestTheClaimIsRecomputable:
    def test_publishing_writes_a_digest_a_hash_and_a_chain_head(
        self, loaded, organizer, audit_trail
    ):
        record = publication.publish(loaded, organizer)

        assert record.input_digest and len(record.input_digest) == 64
        assert record.results_hash and len(record.results_hash) == 64
        assert record.audit_chain_head, "the chain head is the whole of D-09"
        assert record.audit_chain_head == publication.chain_head(loaded)
        assert record.ranking, "a publication with no ranking hashes nothing"

    def test_an_empty_chain_publishes_an_empty_head_rather_than_a_placeholder(
        self, loaded, organizer
    ):
        """**The honest degenerate case, asserted rather than skipped.**

        A fresh database has no audit entries, so there is no head. Writing a
        placeholder hash here would be worse than writing nothing: it would look
        like a chain head to anyone comparing it, and would differ from the real
        chain's first entry -- so every later comparison would report a tamper
        that did not happen.
        """
        assert publication.chain_head(loaded) == ""
        record = publication.publish(loaded, organizer)
        assert record.audit_chain_head == ""
        assert record.results_hash, "the ranking hash is still computed and still means something"

    def test_the_digest_survives_a_full_wipe_and_restore(self, loaded, organizer, tmp_path):
        """**The centrepiece.** Export, wipe, import, recompute -- same digest.

        This is the only test in the project that ties the two halves of FEAT-07
        together. If the digest depended on anything the archive does not carry,
        the publication claim would be unverifiable by the only party who can
        actually check it, and nobody would find out until a judge tried.
        """
        from reviewer.io import bundle

        before = publication.publish(loaded, organizer).input_digest

        first = tmp_path / "pub-1"
        bundle.export_archive(first, exclude=BOOKKEEPING)
        bundle.clear_all()
        bundle.import_archive(first)

        assert publication.input_digest(loaded) == before, (
            "the digest does not survive a round trip, so 'anyone holding the "
            "export can recompute it' is false and the hash is a fingerprint "
            "rather than evidence"
        )

    def test_the_ranking_hash_survives_the_same_round_trip(self, loaded, organizer, tmp_path):
        """The ranking, not just the digest, has to come back identical."""
        from reviewer.io import bundle

        record = publication.publish(loaded, organizer)
        archive = tmp_path / "pub-2"
        bundle.export_archive(archive, exclude=BOOKKEEPING)
        bundle.clear_all()
        bundle.import_archive(archive)

        rows = publication.ranking_for(loaded, organizer)
        assert publication.results_hash(rows, record.input_digest) == record.results_hash


class TestTheHashDetectsAnEdit:
    """The control: the hash has to MOVE when the data changes, or it proves nothing."""

    def test_altering_one_score_changes_the_digest(self, loaded, organizer):
        from reviewer.reviews.models import Score

        before = publication.input_digest(loaded)
        score = Score.objects.filter(review__event=loaded, value__isnull=False).first()
        original = score.value
        score.value = 1
        score.save(update_fields=["value"])
        try:
            assert publication.input_digest(loaded) != before
        finally:
            score.value = original
            score.save(update_fields=["value"])
        assert publication.input_digest(loaded) == before, "the restore must be exact"

    def test_altering_the_ranking_changes_the_hash(self, loaded, organizer):
        rows = publication.ranking_for(loaded, organizer)
        digest = publication.input_digest(loaded)
        original = publication.results_hash(rows, digest)

        tampered = [dict(row) for row in rows]
        tampered[0]["mean"] = 99.0
        assert publication.results_hash(tampered, digest) != original

    def test_the_digest_is_mixed_into_the_ranking_hash(self, loaded, organizer):
        """Otherwise a hash from one set of scores could be presented as the hash
        of another that happens to rank the same."""
        rows = publication.ranking_for(loaded, organizer)
        digest = publication.input_digest(loaded)
        original = publication.results_hash(rows, digest)
        assert publication.results_hash(rows, "0" * 64) != original

    def test_the_hash_records_how_the_ranking_was_computed(self, loaded, organizer):
        """**Dropping `normalization` from the hash is undetectable any other way.**

        Removing it leaves every hash consistent with every other hash -- the
        round trip still matches, an edit still moves it, the digest is still mixed
        in -- so no existing test notices. The mutation harness reported it
        NOT DETECTED and was right.

        The only way to catch it is to assert the field's *influence* directly:
        two rankings whose numbers are identical and whose `normalization` differs
        must hash differently. **A hash that cannot distinguish a corrected
        ranking from an uncorrected one is not a claim about how the ranking was
        produced** -- and the day the normalization estimator is switched on, that
        is exactly the confusion.
        """
        rows = publication.ranking_for(loaded, organizer)
        digest = publication.input_digest(loaded)
        as_shipped = publication.results_hash(rows, digest)

        relabelled = []
        for row in rows:
            copy = dict(row)
            copy["normalization"] = "corrected-by-estimator"
            relabelled.append(copy)

        assert publication.results_hash(relabelled, digest) != as_shipped, (
            "the hash does not record whether the ranking was normalized, so a "
            "corrected ranking and an uncorrected one are the same claim"
        )

    def test_the_cosmetic_rename_does_not_invalidate_the_publication(self, loaded, organizer):
        """A hash that moved on a rename would be one more reason to avoid
        re-publishing, which is the opposite of what this table is for."""
        from reviewer.projects.models import Project

        rows = publication.ranking_for(loaded, organizer)
        digest = publication.input_digest(loaded)
        original = publication.results_hash(rows, digest)

        project = Project.objects.get(pk="prj_01")
        project.title = "Renamed"
        project.save(update_fields=["title"])
        assert (
            publication.results_hash(publication.ranking_for(loaded, organizer), digest) == original
        )


class TestPublishingIsARowAndNotASingleton:
    def test_publishing_twice_keeps_both(self, loaded, organizer):
        """Publishing after fixing a typo is a real workflow, and overwriting the
        first hash would destroy exactly the evidence this table exists to keep."""
        first = publication.publish(loaded, organizer)
        second = publication.publish(loaded, organizer)

        assert first.pk != second.pk
        assert first.results_hash == second.results_hash, (
            "unchanged data should hash the same; a difference means the hash "
            "depends on something that is not the result"
        )

    def test_an_edit_makes_the_second_publication_disagree(self, loaded, organizer):
        from reviewer.reviews.models import Score

        first = publication.publish(loaded, organizer)
        score = Score.objects.filter(review__event=loaded, value__isnull=False).first()
        original = score.value
        score.value = 1
        score.save(update_fields=["value"])
        try:
            second = publication.publish(loaded, organizer)
        finally:
            score.value = original
            score.save(update_fields=["value"])

        assert second.results_hash != first.results_hash, (
            "a changed result produced the same hash, so the hash is not a claim about the result"
        )

    def test_publishing_needs_an_organizer(self, loaded):
        from reviewer.isolation import Actor

        visitor = Actor.anonymous(loaded)
        with pytest.raises(PermissionError):
            publication.publish(loaded, visitor)


class TestD09Replication:
    def test_the_hash_and_chain_head_land_in_every_signed_record(
        self, loaded, organizer, signed_record
    ):
        record = publication.publish(loaded, organizer)
        signed_record.refresh_from_db()

        assert signed_record.statement["results_hash"] == record.results_hash
        assert signed_record.statement["audit_chain_head"] == record.audit_chain_head

    def test_the_replication_is_reported_rather_than_assumed(
        self, loaded, organizer, signed_record
    ):
        record = publication.publish(loaded, organizer)
        report = publication.replication_report(loaded, record)
        assert report["agrees"] == 1
        assert report["disagrees"] == 0
        assert report["total"] == 1

    def test_a_record_signed_against_an_older_result_is_not_overwritten(
        self, loaded, organizer, signed_record
    ):
        """**The equivocation case, and the reason this exists.** A judge signed
        hash A, the organizer changed the result to hash B. Overwriting the
        judge's record would erase the only evidence that the result moved after
        they signed -- which is the whole thing replication was for."""
        first = publication.publish(loaded, organizer)

        from reviewer.reviews.models import Score

        score = Score.objects.filter(review__event=loaded, value__isnull=False).first()
        original = score.value
        score.value = 1
        score.save(update_fields=["value"])
        try:
            second = publication.publish(loaded, organizer)
        finally:
            score.value = original
            score.save(update_fields=["value"])

        signed_record.refresh_from_db()
        assert second.results_hash != first.results_hash
        assert signed_record.statement["results_hash"] == first.results_hash, (
            "a judge's signed record was overwritten, destroying the evidence that "
            "the result changed after they signed"
        )

        report = publication.replication_report(loaded, second)
        assert report["disagrees"] == 1, "and the disagreement is visible, not hidden"

    def test_the_statement_is_where_it_goes_and_not_a_column_we_own(self, signed_record):
        """A column would be ours to rewrite; a rewritten column is invisible."""
        assert "results_hash" not in {f.name for f in signed_record._meta.get_fields()}


class TestTheFieldListAndTheHashAgree:
    """F-98: the two were written separately and drifted."""

    def test_the_hash_covers_exactly_the_named_fields(self, loaded, organizer):
        """The docstring said "exactly ``RANKING_FIELDS``" and it was false."""
        row = publication.ranking_for(loaded, organizer)[0]
        assert set(publication._hashable(row)) == set(publication.RANKING_FIELDS)

    def test_every_named_field_is_actually_present_in_a_row(self, loaded, organizer):
        """A named field the rows do not have contributes a constant, which is
        the same as not being in the hash at all -- while looking covered."""
        row = publication.ranking_for(loaded, organizer)[0]
        for name in publication.RANKING_FIELDS:
            assert name in row, f"RANKING_FIELDS names {name!r}, which no ranking row has"

    def test_changing_any_named_field_changes_the_hash(self, loaded, organizer):
        """The strong form: every named field provably reaches the hash.

        **A field that is constant across all rows is not decoration.** The first
        version of this file asserted that, and it flagged ``normalization`` --
        which is constant *on purpose*, because "this whole ranking is
        unnormalized" is the claim. The assertion was wrong about the field and
        the field was right. Perturbing each field is the property that actually
        matters and it holds for a constant field too.
        """
        digest = publication.input_digest(loaded)
        rows = publication.ranking_for(loaded, organizer)
        base = publication.results_hash(rows, digest)
        for name in publication.RANKING_FIELDS:
            altered = [dict(row) for row in rows]
            altered[0][name] = "SENTINEL"
            assert publication.results_hash(altered, digest) != base, (
                f"{name!r} is in RANKING_FIELDS but changing it does not move the hash"
            )


class TestTheCommand:
    def test_show_only_writes_nothing(self, loaded, capsys):
        from django.core.management import call_command

        call_command("publish_results", "--show-only")
        from reviewer.audit.models import ResultPublication

        assert ResultPublication.objects.count() == 0
        assert "WOULD PUBLISH" in capsys.readouterr().out

    def test_it_publishes_and_says_the_hash_is_recomputable(self, loaded, capsys):
        from django.core.management import call_command

        call_command("publish_results")
        out = capsys.readouterr().out
        assert "PUBLISHED" in out
        assert "re-derivable" in out, (
            "the command should say the hashes are recomputable, or a reader will "
            "assume they are a secret we hold"
        )
