"""rubrics: Rubric and Criterion -- versioned, because two rubrics are not one scale.

FEAT-02, initial schema. Serves bible/05 §5.

Rubrics are versioned (unique on event/name/version) and every Review records
the version it was scored under. A judge on v1 and a judge on v2 are not
comparable, and a normalization argument that silently mixes them is not an
argument.

Criterion.weight is a Decimal, not a float: 0.4 + 0.35 + 0.25 is
0.9999999999999999 in IEEE 754, and an organizer told their rubric is
malformed when it is not learns to distrust every other number shown to them.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("scale_min", models.SmallIntegerField(default=1)),
                ("scale_max", models.SmallIntegerField(default=5)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubrics",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "rubrics_rubric",
                "ordering": ["event_id", "name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Relative weight. Normalised at read time; never stored pre-summed.",
                        max_digits=6,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "rubrics_criterion",
                "ordering": ["rubric_id", "position", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="rubric",
            constraint=models.UniqueConstraint(
                fields=("event", "name", "version"),
                name="rubrics_rubric_event_name_ver_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubric",
            constraint=models.CheckConstraint(
                condition=models.Q(("scale_min__lt", models.F("scale_max"))),
                name="rubrics_rubric_scale_ordered",
                violation_error_message="scale_min must be below scale_max; a one-point scale is a config error.",
            ),
        ),
        migrations.AddIndex(
            model_name="criterion",
            index=models.Index(
                fields=["rubric_id", "position"], name="rubrics_criterion_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.UniqueConstraint(
                fields=("rubric", "key"), name="rubrics_criterion_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)),
                name="rubrics_criterion_weight_positive",
                violation_error_message="A criterion weight must be greater than zero.",
            ),
        ),
    ]
