"""webhooks: WebhookEndpoint and WebhookDelivery -- the schema for a cut feature.

FEAT-02, initial schema. Serves D-14 / F-20.

Webhook DELIVERY is cut: two hours, zero points on all four criteria, and the
SSRF mitigation it needs (scheme allowlist, DNS resolution checked against
private ranges, redirect limit) is a real bug class written from scratch under
time pressure. What ships is both models and a 501 view, so whoever extends
this has somewhere to put the code.

Note the https-only CHECK constraint. The scheme allowlist lives in the SCHEMA
rather than in the cut code, so a future implementation cannot start from
"whatever URL validates". And `secret_ref` is a reference, not a secret field:
a column named `secret` that is never written is a column someone will later
write an unhashed value into.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "secret_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference to a signing secret. Delivery is not implemented; see D-14.",
                        max_length=128,
                    ),
                ),
                ("events", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_endpoint",
                "ordering": ["event_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_delivery",
                "ordering": ["endpoint_id", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["event", "active"], name="webhooks_ep_event_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookendpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("url__startswith", "https://")),
                name="webhooks_endpoint_https_only",
                violation_error_message="A webhook URL must be https; http is plaintext to a third party.",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["endpoint", "status"], name="webhooks_dl_endpoint_idx"
            ),
        ),
    ]
