"""audit: AuditEntry and ResultPublication -- append-only, hash-chained, and the anchor.

FEAT-02, initial schema. Serves D-08 and bible/05 §9, §9c.

AuditEntry carries seq / prev_hash / entry_hash / omitted_since_prev. The last
column is the design: rate-limited audit sampling plus a hash chain is
incoherent, because a gap in the sequence is indistinguishable from a deleted
entry. Putting the dropped count INSIDE the chain turns the gap into a
provable, disclosed fact instead of a tamper signal. The writer that computes
the hashes is FEAT-05; this migration ships the columns the chain needs and the
manager that makes update() and delete() raise.

ResultPublication.results_hash is the content hash an untrusted organizer
cannot quietly alter: input_digest is re-derivable from the raw scores and the
ranking is re-computable by anyone running the published method, so the hash is
a claim and the export is the evidence. One row per publication, never
overwritten -- publishing twice after fixing a typo is real work, and
overwriting would destroy exactly the evidence this table exists to keep.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        ("rubrics", "0001_initial_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=64)),
                ("object_type", models.CharField(blank=True, max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("ip_hash", models.CharField(blank=True, max_length=128)),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="Monotonic per event. A gap here is either a disclosed omission or a tamper signal."
                    ),
                ),
                ("prev_hash", models.CharField(blank=True, default="", max_length=64)),
                ("entry_hash", models.CharField(blank=True, default="", max_length=64)),
                ("omitted_since_prev", models.PositiveIntegerField(default=0)),
                ("scope_reason", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "audit_auditentry",
                "ordering": ["event_id", "seq"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="audit_entry_event_idx"
                    ),
                    models.Index(
                        fields=["event", "actor", "action"],
                        name="audit_entry_actor_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "seq"), name="audit_entry_event_seq_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResultPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField()),
                ("input_digest", models.CharField(max_length=64)),
                ("ranking", models.JSONField(default=list)),
                ("results_hash", models.CharField(max_length=64)),
                (
                    "audit_chain_head",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_publications",
                        to="events.event",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubric_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_publications",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "audit_resultpublication",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-published_at"], name="audit_pub_event_idx"
                    )
                ],
            },
        ),
    ]
