"""comments: Comment.

FEAT-02, initial schema. Serves bible/05 §7 and bible/07 §4.

Bodies are rendered escaped, always, with no raw HTML and no `|safe` anywhere in
the project. `status` (visible/pending/hidden) keeps a moderated comment's row
rather than deleting it, so the organizer can see that it existed and why it is
not shown: a filtered comment is indistinguishable from one that was never
posted, and that ambiguity is how a moderation queue becomes untrustworthy.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        ("projects", "0001_initial_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_label", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("pending", "Pending"),
                            ("hidden", "Hidden"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="events.event",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments_moderated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "comments_comment",
                "ordering": ["project_id", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="comments_cm_project_idx"
                    ),
                    models.Index(
                        fields=["event", "status"], name="comments_cm_event_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["visible", "pending", "hidden"])
                        ),
                        name="comments_comment_status_known",
                        violation_error_message="Unknown comment status.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("parent_id", models.F("pk")), _negated=True
                        ),
                        name="comments_comment_no_self_parent",
                        violation_error_message="A comment cannot be its own parent.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("body", ""), _negated=True),
                        name="comments_comment_body_not_empty",
                        violation_error_message="An empty comment is not a comment.",
                    ),
                ],
            },
        ),
    ]
