"""teams: drop UNIQUE (event, name) on Team, because the fixture violates it.

FEAT-03, and this is a **measurement**, not a preference. The loader for
`fixtures.json` raised::

    IntegrityError: UNIQUE constraint failed: teams_team.event_id, teams_team.name

on the organizers' own dataset, because **40 teams carry 36 distinct names**:
``StillTrail`` three times (``tm_03``, ``tm_30``, ``tm_40``), ``OpenSignal``
twice, ``AmberSwitch`` twice. Two of the colliding teams own different
projects, so it is a property of the data and not a fixture typo.

A constraint the published dataset violates is a constraint that makes our own
loader un-runnable, and the same argument as the constraint this app already
declines to add -- "one team per user per event" -- applies with more force:
two teams named "Team Rocket" at one hackathon is a Tuesday, not a data error.

Kept, deliberately: ``UNIQUE (event, slug)``. A slug is derived, so it is the
column that has to be unambiguous for a URL to mean one team, and
``reviewer.importer.loader._entity_slug`` is what makes it derivable and unique
on lossy names.

The naming and the reasoning are in ``reviewer/teams/models.py``; this file
exists so the history says a constraint was tried against real data and
corrected, rather than a constraint that was quietly never written.
"""

# Generated by Django 5.2.17, then documented. The operation is exactly what
# `makemigrations` produced for the Meta change; only the docstring is ours.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial_schema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="teams_team_event_name_uniq",
        ),
    ]
