"""ballots: Ballot and Vote -- the randomised order and the deduplication identity.

FEAT-02, initial schema. Serves bible/05 §7 and D-12, D-13.

Ballot.order is the per-voter permutation and Ballot.seed is what produced it:
stable per voter, random across voters. That kills position bias within a ballot
while preventing a voter re-rolling the order by refreshing. Storing the seed
means the order can be re-derived for the audit trail instead of merely
asserted.

Vote.ip_hash and Vote.user_agent_hash are HASHES, salted per event, and the
salt is rotatable. We need duplicate detection without becoming a database of
everyone's home address -- which is the entire reason the raw value is not kept.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        ("projects", "0001_initial_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voter_key", models.CharField(max_length=128)),
                ("seed", models.CharField(max_length=128)),
                ("order", models.JSONField(default=list)),
                ("cast_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "ballots_ballot",
                "ordering": ["event_id", "cast_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "voter_key"],
                        name="ballots_ballot_ev_voter_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "voter_key"), name="ballots_ballot_voter_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voter_key", models.CharField(max_length=128)),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Defaults to one. Stored rather than counted so quadratic voting is possible.",
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=128)),
                ("user_agent_hash", models.CharField(blank=True, max_length=128)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="events.event",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "ballots_vote",
                "ordering": ["event_id", "project_id"],
                "indexes": [
                    models.Index(
                        fields=["event", "project", "voter_key"],
                        name="ballots_vote_tally_idx",
                    ),
                    models.Index(
                        fields=["event", "voter_key"], name="ballots_vote_voter_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "project", "voter_key"),
                        name="ballots_vote_dedup_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight__gte", 1)),
                        name="ballots_vote_weight_positive",
                        violation_error_message="A vote's weight is at least one.",
                    ),
                ],
            },
        ),
    ]
