"""projects: Project -- including the duplicate submission the fixture is built around.

FEAT-02, initial schema. Serves bible/05 §4 and bible/04 §3.3.

  * Project.id is a CharField primary key preserving the fixture's identifier
    ("prj_07"), and `supersedes` is a self-FK with BOTH rows kept. Nothing is
    deduplicated on load: a lossy import path quietly discards an organizer's
    data.
  * title is NOT unique. Two fixture projects share the title "Dry Harbour",
    and a unique index on user-supplied text is a support incident waiting to
    happen. Uniqueness lives on (team, slug).
  * track is NOT NULL. The assignment model is track-scoped, so a project with
    no track has no meaning.
  * status is constrained in the database as well as in `choices`, because
    `choices` is not a CHECK constraint and an unknown status is a project that
    is in no gallery and no export.
  * The four index prefixes are the three hot paths FEAT-02 names: the event
    gallery, the team/supersede view, and the positional slice run.py reads.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        ("teams", "0001_initial_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("slug", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=300)),
                ("summary", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("video_url", models.URLField(blank=True, max_length=500)),
                ("live_url", models.URLField(blank=True, max_length=500)),
                ("repo_url", models.URLField(blank=True, max_length=500)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_answers", models.JSONField(blank=True, default=dict)),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="events.event",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="teams.team",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="events.track",
                    ),
                ),
            ],
            options={
                "db_table": "projects_project",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["event", "track", "status"],
                        name="projects_proj_gal_idx",
                    ),
                    models.Index(
                        fields=["event", "team"], name="projects_proj_event_team_idx"
                    ),
                    models.Index(
                        fields=["event", "submitted_at"],
                        name="projects_proj_submitted_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "slug"), name="projects_project_team_slug_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["draft", "submitted", "withdrawn"])
                        ),
                        name="projects_project_status_known",
                        violation_error_message="Unknown project status.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("supersedes_id", models.F("pk")), _negated=True
                        ),
                        name="projects_project_no_self_supersede",
                        violation_error_message="A project cannot supersede itself.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "draft"), ("submitted_at__isnull", True)
                            ),
                            ("status__in", ["submitted", "withdrawn"]),
                            _connector="OR",
                        ),
                        name="projects_project_draft_has_no_submitted_at",
                        violation_error_message="A draft cannot have a submission timestamp.",
                    ),
                ],
            },
        ),
    ]
