"""events: Event, Track, Prize -- the tenant boundary and its policy.

FEAT-02, initial schema. Serves bible/05 §2.

Three things here are load-bearing and each was a decision:

  * Event.id is a CharField primary key that keeps the fixture's identifier
    verbatim ("evt_01"), so a curl transcript in the README is checkable
    against a row by string comparison.
  * submissions_close / submissions_open / judging_closes_at are three real
    timestamps rather than a status enum, because the organizers' T1-3 check
    depends on the deadline being a DATE THE CODE READS. The shipped fixture's
    close date is in the past, so the portal is born closed.
  * Track.target_reviews_per_project is NULLABLE and inherits from the event.
    trk_01 and trk_08 are zero-slack at a target of 3, and a single event-wide
    integer cannot express "3 everywhere except these two".
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("submissions_open", models.DateTimeField(blank=True, null=True)),
                ("submissions_close", models.DateTimeField()),
                ("judging_closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "results_state",
                    models.CharField(
                        choices=[("hidden", "Hidden"), ("published", "Published")],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                (
                    "voting_mode",
                    models.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("open_link", "Open link"),
                            ("email_gated", "Email gated"),
                            ("authenticated", "Authenticated"),
                        ],
                        default="closed",
                        max_length=20,
                    ),
                ),
                ("voting_opens_at", models.DateTimeField(blank=True, null=True)),
                ("voting_closes_at", models.DateTimeField(blank=True, null=True)),
                ("reviews_per_project", models.PositiveIntegerField(default=3)),
                (
                    "rubric_weights_locked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "events_event",
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reviews_per_project__gte", 1)),
                        name="events_event_target_positive",
                        violation_error_message="A review target of zero can never be satisfied.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "target_reviews_per_project",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "events_track",
                "ordering": ["event_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to="events.event",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prizes",
                        to="events.track",
                    ),
                ),
            ],
            options={
                "db_table": "events_prize",
                "ordering": ["event_id", "-amount_cents"],
            },
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["event", "id"], name="events_track_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="events_track_event_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("event", "slug"), name="events_track_event_slug_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="prize",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gte", 0)),
                name="events_prize_amount_non_negative",
                violation_error_message="A negative prize is a data error, not a debt.",
            ),
        ),
        migrations.AddConstraint(
            model_name="prize",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="events_prize_currency_iso3",
                violation_error_message="Currency is a 3-letter code; the panel is in five countries.",
            ),
        ),
    ]
