# Generated by Django 5.2.17 on 2026-09-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="assignment_seed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="judge_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("judge_capacity__isnull", True),
                    ("judge_capacity__gte", 1),
                    _connector="OR",
                ),
                name="events_event_capacity_positive",
                violation_error_message="A per-judge capacity of zero can never assign anything. NULL means 'no organizer cap' and is the only other allowed value.",
            ),
        ),
    ]
