"""credentials: JudgeCredential and SignedRecord.

FEAT-02, initial schema. Serves D-09, D-10 and bible/05 §9, §9b, §9c.

The private key never lands in this database -- only the public half, which is
all a verifier needs. Keys live on their OWN Docker volume, because our own
verification checklist runs `docker compose down -v && up` twice and keys on the
database volume would wipe every record quoted in the README and the demo video.

SignedRecord stores an in-toto Statement v1 verbatim inside a DSSE envelope, not
a signature over a canonical JSON blob we invented. DSSE signs BYTES, so a
verifier never has to agree with us about key ordering, number formatting or
Unicode normalisation, and `cosign` or any in-toto verifier can check our
records with tooling that already exists.

audit_chain_head on SignedRecord is what replaces a Merkle transparency log
(D-09): certificate transparency's value is WITNESSING and this project has no
witness, so instead the head is replicated into N independently signed records
held by N people who are not the organizer.
"""

# Generated by Django 5.2.17 on 2026-09-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_key", models.CharField(max_length=128)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("signature", models.TextField(blank=True)),
                (
                    "record_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_credentials",
                        to="events.event",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credentials_judgecredential",
                "ordering": ["event_id", "judge_id"],
            },
        ),
        migrations.CreateModel(
            name="SignedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        help_text="Natural key from the source system. Null for rows this portal created.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement", models.JSONField()),
                ("envelope", models.JSONField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("record_hash", models.CharField(max_length=64)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_records",
                        to="credentials.judgecredential",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed_records",
                        to="events.event",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credentials_signedrecord",
                "ordering": ["event_id", "judge_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="judgecredential",
            constraint=models.UniqueConstraint(
                fields=("event", "judge"), name="credentials_cred_event_judge_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="signedrecord",
            index=models.Index(
                fields=["event", "judge"], name="credentials_rec_ev_judge_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="signedrecord",
            constraint=models.UniqueConstraint(
                fields=("event", "judge"), name="credentials_record_event_judge_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="signedrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("record_hash", ""), _negated=True),
                name="credentials_record_hash_present",
                violation_error_message="A signed record with no hash cannot be referenced.",
            ),
        ),
    ]
